const CONFIG = {Crush}
    introTitle: 'Hi cưng!!!',
    introDesc: `Cậu có biết cậu khác những vì sao ở điểm nào không? Sao ở trên trời, cậu ở trong tim tớ đó`,
    btnIntro: 'Next<3',
    title: 'Phải chăng cậu cũng thích tớ',
    desc: 'Hay chỉ là có mình tớ :(( ',
    btnYes: 'Thích cậu đã lâu 🥰',
    btnNo: 'Không, em gái à :)',
    question:'Mọi người thì thích trà sữa. Còn tui thì thích trà trộn vào tim cậu ó. ❤',
    btnReply: 'Next <3',
    reply: 'thanks so much <3',
    mess: 'tui biết gòi. i love you more than i can say',
    messDesc: 'chúc cậu có được toi hehe',
    btnAccept: 'hí hí ok luôn',
    messLink: 
